### ISSUE TITLE
Error in tweet-interpreter, terminal-interpreter missing dependency

### ISSUE THREAD

**Issue by ev45ive** [SimonRichardson/fantasia#1]
Hello, i try to run tweet-interpreter and get this error

```
node node_modules/fantasia/examples/interpreter-tweet.js 
-----------------------------------
Getting tweets for user  1

/home/mkulesza/projects/query/node_modules/fantasia/src/free.js:59
            return f(x).chain(function(y) {
                        ^
TypeError: Object Free.Chain(Free.Return([object Object]), function (tweets) {
            // FIXME : This should pass back array of tweets, not a mapped version of tweets [x, y, z] rather than [x][y][z]!
            console.log('>', tweets);
            var x = tweets.map(function(tweet) {
                console.log('>>', tweet);
                return getUser(tweet.id).chain(function(user) {
                    console.log('>>>', user);
                    return singleton(tweet.str, user);
                });
            });
            console.log(x);
            return x;
        }),Free.Chain(Free.Return([object Object]), function (tweets) {
            // FIXME : This should pass back array of tweets, not a mapped version of tweets [x, y, z] rather than [x][y][z]!
            console.log('>', tweets);
            var x = tweets.map(function(tweet) {
                console.log('>>', tweet);
                return getUser(tweet.id).chain(function(user) {
                    console.log('>>>', user);
                    return singleton(tweet.str, user);
                });
            });
            console.log(x);
            return x;
        }),Free.Chain(Free.Return([object Object]), function (tweets) {
            // FIXME : This should pass back array of tweets, not a mapped version of tweets [x, y, z] rather than [x][y][z]!
            console.log('>', tweets);
            var x = tweets.map(function(tweet) {
                console.log('>>', tweet);
                return getUser(tweet.id).chain(function(user) {
                    console.log('>>>', user);
                    return singleton(tweet.str, user);
                });
            });
            console.log(x);
            return x;
        }) has no method 'chain'
    at definitions.resume.cata.Left (/home/mkulesza/projects/query/node_modules/fantasia/src/free.js:59:25)
    at definitions.cata (/home/mkulesza/projects/query/node_modules/daggy/daggy.js:134:40)
    at definitions.Free.foldMap (/home/mkulesza/projects/query/node_modules/fantasia/src/free.js:57:26)
    at Function.Free.runFC (/home/mkulesza/projects/query/node_modules/fantasia/src/free.js:31:14)
    at /home/mkulesza/projects/query/node_modules/fantasia/examples/interpreter-tweet.js:130:22
    at Object.<anonymous> (/home/mkulesza/projects/query/node_modules/fantasia/examples/interpreter-tweet.js:132:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

and terminal missing some dependency

```
node node_modules/fantasia/examples/interpreter-terminal.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'readline-sync'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/mkulesza/projects/query/node_modules/fantasia/examples/interpreter-terminal.js:5:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

```

**Comment by SimonRichardson** [comment]
Yeah, I'm reading about how you implement that interpreter. I've fixed the others so they run correctly, but I need to do a lot more reading.

I'll fix the `readline-sync` issue in the next commit.

**Comment by ev45ive** [comment]
Thanks, great work btw! I am trying to catch up, but it takes some time without types ;-) 

Please think about adding comments, maybe with pseud-types or just description what are steps - might help you get clear view and would definatelly help me follow :dancer: code. 

As for Interpreter tourorials i found those two to be most interesting if you haven't seen those already:
http://underscore.io/blog/posts/2015/04/14/free-monads-are-simple.html
http://futurice.com/blog/an-example-of-functional-design -> "Here be dragons" section

I will spend more time with debugger on other ones and hopefully catch up ;-)

**Comment by SimonRichardson** [comment]
Excellent I didn't know about the second link, thanks for this.

**Comment by SimonRichardson** [comment]
fyi: to install the `readline-sync` you need to install it from `devDependencies`, so it's a case of `npm install --dev`.

**Comment by SimonRichardson** [comment]
I'm still working on this! It turns out it's quite difficult because we lose the context somehow and it's hard to track down. I suspect that I'm calling applicative wrongly when running sequence on the tweets. 

I'll keep going as this is what really interests me concerning free monads.

**Comment by SimonRichardson** [comment]
This is [fixed now](https://github.com/SimonRichardson/fantasia/commit/25865cf506ed429d50a2df4b1c6d55518fb5ef75).

I added the fantasy-quickcheck library to test the various laws (monad, functor and applicative) as I couldn't see what was broken. Turns out that it was the applicative method that was broken. I wished I added the library sooner, lessoned learned to us all!!
